# Generated by Django 5.0.2 on 2024-03-08 16:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='dateOfImage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='descriptionImage',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='photo',
            name='nameImage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploadDateImage',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 8, 16, 21, 57, 525581)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='categoryImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
    ]
