# Generated by Django 5.0.2 on 2024-03-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_photo_dateofimage_photo_descriptionimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='categoryImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
    ]
