# Generated by Django 5.0.2 on 2024-03-08 16:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_photo_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='categoryAudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
        migrations.AddField(
            model_name='audio',
            name='dateOfAudio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='descriptionAudio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='audio',
            name='nameAudio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='audio',
            name='uploadDateAudio',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 8, 16, 30, 33, 971558)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='categoryVideo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
        migrations.AddField(
            model_name='video',
            name='dateOfVideo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='descriptionVideo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='nameVideo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='uploadDateVideo',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 8, 16, 30, 50, 98457)),
            preserve_default=False,
        ),
    ]
