# Generated by Django 5.0.2 on 2024-03-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_audio_categoryaudio_audio_dateofaudio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('content_kz', models.TextField()),
                ('content_ru', models.TextField()),
            ],
        ),
    ]
