# Generated by Django 5.0.2 on 2024-03-28 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_file', models.FileField(upload_to='article/')),
                ('nameArticle', models.CharField(blank=True, max_length=100)),
                ('partArticle', models.CharField(blank=True, max_length=500)),
                ('dateOfAudio', models.DateField(blank=True, null=True)),
                ('uploadDateAudio', models.DateTimeField(auto_now_add=True)),
                ('categoryArticle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
    ]
