# Generated by Django 5.0.2 on 2024-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_article_partarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='dateOfAudio',
            new_name='dateOfArticle',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='uploadDateAudio',
            new_name='uploadDateArticle',
        ),
        migrations.AddField(
            model_name='article',
            name='nameAuthor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
